name: tms_app
description: TMS Learn Tech App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  timeago: ^3.5.0
  flutter_html: ^3.0.0-beta.2
  share_plus: ^11.0.0

  # ðŸŒ UI & Routing
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  go_router: ^14.0.0
  font_awesome_flutter: ^10.8.0

  # âš™ï¸ Core & DI
  get: ^4.6.5
  get_it: ^7.6.0
  mockito: ^5.0.17
  # ðŸš€ Gá»i API + xá»­ lÃ½ JSON
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1
  logger: ^2.0.2
  url_launcher: ^6.1.12

  # ðŸ“¦ Tiá»‡n Ã­ch báº¡n Ä‘ang dÃ¹ng
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.2
  string_similarity: ^2.0.0
  intl: ^0.19.0
  image_picker: ^1.0.7
  percent_indicator: ^4.2.5
  fl_chart: ^0.63.0
  shared_preferences: ^2.5.3
  google_sign_in: ^6.2.2
  carousel_slider: ^5.0.0
  permission_handler: ^12.0.0+1
  shimmer: ^3.0.0
  confetti: ^0.8.0
  path_provider: ^2.1.5
  open_file: ^3.5.10
  app_settings: ^6.1.1
  connectivity_plus: ^5.0.2
  video_player: ^2.9.5
  cached_network_image: ^3.3.1
  chewie: ^1.11.3
  flutter_secure_storage: ^8.0.0
  #cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_pdfview: ^1.3.1
  http: ^1.1.0

  # ðŸ›  Dev tool sinh code tá»± Ä‘á»™ng
  build_runner: ^2.4.7
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  analyzer: ^6.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/documents/
    - assets/images/banners/
    - assets/images/courses/
    # - assets/images/onboarding/
    - assets/icons/
    - assets/images/
